### ISSUE TITLE
Error in adding new record to Material table

### ISSUE THREAD

**Issue by frankvdh** [arkypita/LaserGRBL#1042]
Deleted several rows from the bottom of the database that would never be applicable to me, then clicked on the blank "Model" field to add a new record and got this error message:

LaserGrbl v3.5.0.0
Grbl v1.1h
Wrapper: UsbSerial
Win 10, Professional, 10.0.18363.0 (7)

TypeOf exception  [System.Data.DeletedRowInaccessibleException]
Exception message [Deleted row information cannot be accessed through the row.]
Exception source  [System.Data], thread [Main Thread]
Exception method  [Int32 GetDefaultRecord()]

   ----------- stack trace -----------
   at System.Data.DataRow.GetDefaultRecord()
   at System.Data.DataRow.get_Item(DataColumn column)
   at LaserGRBL.PSHelper.MaterialDB.MaterialsRow.get_Model() in E:\LaserGRBL\LaserGRBL\PSHelper\MaterialDB.Designer.cs:line 721
   at LaserGRBL.PSHelper.MaterialDB.MaterialsDataTable.OnTableNewRow(DataTableNewRowEventArgs e) in E:\LaserGRBL\LaserGRBL\PSHelper\MaterialDB.cs:line 37
   at System.Data.DataView.AddNew()
   at System.Data.DataView.System.ComponentModel.IBindingList.AddNew()
   at System.Windows.Forms.BindingSource.AddNew()
   at System.Windows.Forms.CurrencyManager.AddNew()
   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.AddNew()
   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.OnNewRowNeeded()
   at System.Windows.Forms.DataGridView.OnRowEnter(DataGridViewCell& dataGridViewCell, Int32 columnIndex, Int32 rowIndex, Boolean canCreateNewRow, Boolean validationFailureOccurred)
   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
Thanks for the bug report. The database functionality is experimental, I still have to do some refinements.

I suggest removing the "visible" flag instead of deleting the records, otherwise these deleted records may re-appear with future updates of LaserGRBL.
