### ISSUE TITLE
Ooops something went wrong...

### ISSUE THREAD

**Issue by LARDEEJAY** [arkypita/LaserGRBL#1173]
Hi I just got this message 2 mins ago and it says to contact you with it.

I am also having problems with the steppers keep locking up and candle freezing often any ideas Lasergrbl said to send you this code...

TypeOf exception  [System.TimeoutException]
Exception message [Wrong number of config param found! (28/31)]
Exception source  [LaserGRBL], thread [Main Thread]
Exception method  [Void RefreshConfig()]

   ----------- stack trace -----------
   at LaserGRBL.GrblCore.RefreshConfig() in E:\LaserGRBL\LaserGRBL\GrblCore.cs:line 763
   at LaserGRBL.GrblConfig.BtnExport_Click(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\GrblConfig.cs:line 175
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I have no idea I am just a noobie to this .

**Comment by arkypita** [comment]
Hi @LARDEEJAY
LaserGRBL is exporting your grbl board configuration. The configuration is made by a few number of parameters stored inside the controller.

LaserGRBL try to read the config from the board, and know how many of this parameters to expect. It is expecting to receive 31 parameters, instead the board returns only 28 parameters.

Can you tell me what kind of board do you have?
Grbl version?
