### ISSUE TITLE
Configuration parser error (LaserGRBL.exe won't load)

### ISSUE THREAD

**Issue by runningyolk** [arkypita/LaserGRBL#1217]
**Hello!
I've been unable to load LaserGRBL because I keep receiving the following error messages:** 

"LaserGRBL.exe - Configuration parser error

Error parsing
C:\Windows\Microsoft.NET\Framework64\v2.0.50727\config\machine.config
Parser returned error 0xC00CE556"

**After clicking 'OK' on this error message the following report from the Exception Manager appears:**

"LaserGrbl v3.8.6.0
 v
Wrapper: UsbSerial
Win 10, Education, 10.0.18363.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll 2.0.50727.9151 (WinRelRS6.050727-9100)

TypeOf exception  [System.Reflection.TargetInvocationException]
Exception message [Exception has been thrown by the target of an invocation.]
Exception source  [mscorlib], thread []
Exception method  [Void _SerializationInvoke(System.Object, System.SignatureStruct ByRef, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)]

   ----------- stack trace -----------
   at System.RuntimeMethodHandle._SerializationInvoke(Object target, SignatureStruct& declaringTypeSig, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at LaserGRBL.ConnectLogForm.InitializeComponent() in E:\LaserGRBL\LaserGRBL\ConnectLogForm.Designer.cs:line 98
   at LaserGRBL.ConnectLogForm..ctor() in E:\LaserGRBL\LaserGRBL\ConnectLogForm.cs:line 27
   at LaserGRBL.MainForm.InitializeComponent() in E:\LaserGRBL\LaserGRBL\MainForm.Designer.cs:line 34
   at LaserGRBL.MainForm..ctor() in E:\LaserGRBL\LaserGRBL\MainForm.cs:line 24
   at LaserGRBL.MainForm..ctor(String[] args) in E:\LaserGRBL\LaserGRBL\MainForm.cs:line 82
   at LaserGRBL.Program.Main(String[] args) in E:\LaserGRBL\LaserGRBL\Program.cs:line 34

Inner exception data
TypeOf exception  [System.TypeInitializationException]
Exception message [The type initializer for 'System.MarvinHash' threw an exception.]
Exception source  [System.Xml], thread []
Exception method  [Void .ctor()]

   ----------- stack trace -----------
   at System.Xml.NameTable..ctor()
   at System.Xml.XmlImplementation..ctor()
   at System.Xml.XmlDocument..ctor()
   at System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at System.Windows.Forms.TableLayoutSettings..ctor(SerializationInfo serializationInfo, StreamingContext context)

Inner exception data
TypeOf exception  [System.ApplicationException]
Exception message [Invalid XML in file 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727\config\machine.config' near element ''.]
Exception source  [mscorlib], thread []
Exception method  [System.ConfigNode Parse(System.String, System.String, Boolean)]

   ----------- stack trace -----------
   at System.ConfigTreeParser.Parse(String fileName, String configPath, Boolean skipSecurityStuff)
   at System.Security.Cryptography.CryptoConfig.InitializeConfigInfo()
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.RandomNumberGenerator.Create()
   at System.MarvinHash.GenerateSeed()
   at System.MarvinHash..cctor()

Inner exception data
TypeOf exception  [System.Runtime.InteropServices.COMException]
Exception message [Exception from HRESULT: 0xC00CE556]
Exception source  [mscorlib], thread []
Exception method  [Void RunParser(System.IConfigHandler, System.String)]

   ----------- stack trace -----------
   at System.ConfigServer.RunParser(IConfigHandler factory, String fileName)
   at System.ConfigTreeParser.Parse(String fileName, String configPath, Boolean skipSecurityStuff)"

**System details:
Windows 10
Sainsmart Genmitsu 3018-PROVER
LaserGRBL v3.8.6

I have tried the following: uninstall/reinstall, replace machine.config from C:\Windows\Microsoft.NET\Framework64\v2.0.50727\config\ with a renamed copy of machine.config.default, and installation of a previous version included on disk.
 
I look forward to any and all help: thank you so much**

**Comment by arkypita** [comment]
Hi. The issue is not directly related to LaserGRBL but with a system component called Microsoft .NET framework that is required for LaserGRBL to run. I suggest a reinstall of .net framework

https://quickbooks.intuit.com/learn-support/en-us/open-programs/manually-fix-microsoft-net-framework-errors/00/203709

As because it is not a LaserGRBL issue, and I cannot test it, the only hint i can give you is to google for the message and check if someone give a solution to this issue

https://www.google.com/search?client=opera&q=Invalid+XML+in+file+%27C%3A%5CWindows%5CMicrosoft.NET%5CFramework64%5Cv2.0.50727%5Cconfig%5Cmachine.config&sourceid=opera&ie=UTF-8&oe=UTF-8
