### ISSUE TITLE
System.ArgumentException Parameter is not valid

### ISSUE THREAD

**Issue by MissEmKay** [arkypita/LaserGRBL#1288]
The error message I copied here.  
LaserGrbl v4.0.5.0
Grbl v1.1f
Wrapper: UsbSerial
Win 7, Starter, 6.1.7601.65536, Service Pack 1 (0)
CLR: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll 4.0.30319.1026 (RTMGDR.030319-1000)

TypeOf exception  [System.ArgumentException]
Exception message [Parameter is not valid.]
Exception source  [System.Drawing], thread [Main Thread]
Exception method  [Int32 get_Width()]

   ----------- stack trace -----------
   at System.Drawing.Image.get_Width()
   at System.Drawing.Image.get_Size()
   at LaserGRBL.RasterConverter.ImageProcessor.ResizeRecalc() in E:\LaserGRBL\LaserGRBL\RasterConverter\ImageProcessor.cs:line 407
   at LaserGRBL.RasterConverter.RasterToLaserForm.PbConverted_Resize(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 688
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.PictureBox.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
In order to solve this problem you should help me to understand in what conditions it presents itself.
What are you doing - exactly - when the error message came out? Can you replicate it or is it sporadic?
