### ISSUE TITLE
Ortur Laser Master II: Error

### ISSUE THREAD

**Issue by LeariWavan** [arkypita/LaserGRBL#1292]
LaserGrbl v3.8.7.0
Grbl v1.1f
Wrapper: UsbSerial
Win 10, Professional, 10.0.19042.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll 2.0.50727.9151 (WinRelRS6.050727-9100)

TypeOf exception  [System.ObjectDisposedException]
Exception message [Safe handle has been closed]
Exception source  [mscorlib], thread []
Exception method  [IntPtr SafeHandleC2NHelper(System.Object, IntPtr)]

   ----------- stack trace -----------
   at System.StubHelpers.StubHelpers.SafeHandleC2NHelper(Object pThis, IntPtr pCleanupWorkList)
   at Microsoft.Win32.UnsafeNativeMethods.WaitCommEvent(SafeFileHandle hFile, Int32* lpEvtMask, NativeOverlapped* lpOverlapped)
   at System.IO.Ports.SerialStream.EventLoopRunner.WaitForCommEvent()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by arkypita** [comment]
Can you try update Microsoft .NET framework? https://www.google.com/search?q=microsoft+.net+framework
Let me know if it solve.
