### ISSUE TITLE
Net Framework

### ISSUE THREAD

**Issue by nonpds** [arkypita/LaserGRBL#1295]
LaserGrbl v4.0.5.0
Grbl v1.1f
Wrapper: UsbSerial
Win 10, Home, 10.0.18363.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4300.0 built by: NET48REL1LAST_C

TypeOf exception  [System.ArgumentException]
Exception message [Parameter is not valid.]
Exception source  [System.Drawing], thread [Main Thread]
Exception method  [Int32 get_Width()]

   ----------- stack trace -----------
   at System.Drawing.Image.get_Width()
   at System.Drawing.Image.get_Size()
   at LaserGRBL.RasterConverter.ImageProcessor.ResizeRecalc() in E:\LaserGRBL\LaserGRBL\RasterConverter\ImageProcessor.cs:line 407
   at LaserGRBL.RasterConverter.RasterToLaserForm.PbConverted_Resize(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 688
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.PictureBox.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version
 - Engraver brand and model
 - Grbl version (i.e. 0.9j, 1.1f)
 - LaserGRBL version

**Additional context**

**Comment by arkypita** [comment]
Same as #1288 
I am working on it, but I am unable to reproduce so it is difficult to me to understand.

In order to solve this problem you should help me to understand in what conditions it presents itself.
What are you doing - exactly - when the error message came out? Can you replicate it or is it sporadic?
