### ISSUE TITLE
System locked when jumping to another image

### ISSUE THREAD

**Issue by jrjpontious** [arkypita/LaserGRBL#1668]
Here was my bug report:

LaserGrbl v4.6.2.0
Grbl v1.1f
Wrapper: UsbSerial
Win 10, Professional, 10.0.19042.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4420.0 built by: NET48REL1LAST_C

TypeOf exception  [System.OverflowException]
Exception message [Value was either too large or too small for an Int32.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Int32 ToInt32(System.Decimal)]

   ----------- stack trace -----------
   at System.Decimal.ToInt32(Decimal d)
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm.AssignMinMaxLimit() in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 78
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm..ctor(GrblCore core) in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 49
   at LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 175
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jrjpontious** [comment]
I need to finish a job VERY SOON as I am going on VC... I can't even continue a new job.  Is there a way to override the Exception Manager to continue?

**Comment by arkypita** [comment]
Hi, look like that you have a damaged grbl configuration (the configuration inside your controller).
LaserGRBL in function AssignMinMaxLimit() read parameter from controller and initialize UI inputbox max and min.

Look like you have a weird value maybe in $30 or other conf.

**Comment by jrjpontious** [comment]
Thank you for your response. I'll check $30 values.. but it won't be until about a week as I am going on VC. I'll let you know if that helps and let you know.. 

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 6, 2021 at 11:47 PM, ***@***.***> wrote:   


Hi, look like that you have a damaged grbl configuration (the configuration inside your controller).
LaserGRBL in function AssignMinMaxLimit() read parameter from controller and initialize UI inputbox max and min.

Look like you have a weird value maybe in $30 or other conf.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
