### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by simeonsimonovski** [arkypita/LaserGRBL#1814]
LaserGrbl v4.8.0.0
Grbl v1.1f
Wrapper: UsbSerial
Win 10, Professional, 10.0.19044.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4470.0 built by: NET48REL1LAST_C

TypeOf exception  [System.Runtime.InteropServices.ExternalException]
Exception message [A generic error occurred in GDI+.]
Exception source  [System.Drawing], thread [Main Thread]
Exception method  [Void Save(System.IO.Stream, System.Drawing.Imaging.ImageCodecInfo, System.Drawing.Imaging.EncoderParameters)]

   ----------- stack trace -----------
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at Tools.Project.ConvertImageToBase64(String imagePath) in E:\LaserGRBL\LaserGRBL\Tools\Project.cs:line 103
   at Tools.Project.AddSettings(Dictionary`2 settings) in E:\LaserGRBL\LaserGRBL\Tools\Project.cs:line 42
   at LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 200
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
Hi
Can you describe to me what are you doing when this error occur, so I can try to replicate it?

**Comment by Programing-gen** [comment]
Hi i'm tring to create file, i set all parameters and when i click create
it pop-up this error. I fixed this by deleting application, reinstalled
older version and upgraded to 4.8 and it worked.
