### ISSUE TITLE
neutral culture.  Make sure "LaserGRBL.UserControls.CommandLog.resources" was correctly embedded or linked into assembly "LaserGRBL" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

### ISSUE THREAD

**Issue by nbukkebag** [arkypita/LaserGRBL#1848]
**Describe the bug**
LaserGrbl v4.8.3.0
 v
Wrapper: UsbSerial
Win 10, Professional, 10.0.22000.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4510.0 built by: NET48REL1LAST_B

TypeOf exception  [System.Resources.MissingManifestResourceException]
Exception message [Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "LaserGRBL.UserControls.CommandLog.resources" was correctly embedded or linked into assembly "LaserGRBL" at compile time, or that all the satellite assemblies required are loadable and fully signed.]
Exception source  [mscorlib], thread []
Exception method  [Void HandleResourceStreamMissing(System.String)]

   ----------- stack trace -----------
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at LaserGRBL.UserControls.CommandLog.InitializeComponent() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\UserControls\CommandLog.Designer.cs:line 50
   at LaserGRBL.UserControls.CommandLog..ctor() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\UserControls\CommandLog.cs:line 25
   at LaserGRBL.ConnectLogForm.InitializeComponent() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\ConnectLogForm.Designer.cs:line 62
   at LaserGRBL.ConnectLogForm..ctor() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\ConnectLogForm.cs:line 27
   at LaserGRBL.MainForm.InitializeComponent() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\MainForm.Designer.cs:line 139
   at LaserGRBL.MainForm..ctor() in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\MainForm.cs:line 27
   at LaserGRBL.MainForm..ctor(String[] args) in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\MainForm.cs:line 87
   at LaserGRBL.Program.Main(String[] args) in C:\Users\Bhimsen.M\Desktop\Bhimsen\3018\LaserGRBL-4.8.3\LaserGRBL-4.8.3\LaserGRBL\Program.cs:line 41

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version
 - Engraver brand and model
 - Grbl version (i.e. 0.9j, 1.1f)
 - LaserGRBL version

**Additional context**

**Comment by arkypita** [comment]
Never seen this error and no idea of how to fix
