### ISSUE TITLE
LaserGRBL 

### ISSUE THREAD

**Issue by finz79** [arkypita/LaserGRBL#1964]
LaserGrbl v4.8.0.0
Grbl v1.1f
Wrapper: UsbSerial
Win 10, Home, 10.0.22000.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4515.0 built by: NET48REL1LAST_C

TypeOf exception  [System.IO.IOException]
Exception message [No more data is available.
]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Void Win32Error(Int32, System.String)]

   ----------- stack trace -----------
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.GetValueNames()
   at System.IO.Ports.SerialPort.GetPortNames()
   at LaserGRBL.ConnectLogForm.TimerUpdate() in E:\LaserGRBL\LaserGRBL\ConnectLogForm.cs:line 213
   at LaserGRBL.MainForm.UpdateTimer_Tick(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\MainForm.cs:line 261
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MARTIN83-DOT** [comment]
LaserGrbl v4.9.4.0
Grbl v1.1h
Wrapper: UsbSerial
Win 10, Home, 10.0.19044.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4515.0 built by: NET48REL1LAST_C

TypeOf exception  [System.OverflowException]
Exception message [Valor demasiado grande o demasiado pequeño para Int32.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Int32 ToInt32(System.Decimal)]

   ----------- stack trace -----------
   en System.Decimal.ToInt32(Decimal d)
   en LaserGRBL.RasterConverter.ConvertSizeAndOptionForm.AssignMinMaxLimit() en E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:línea 88
   en LaserGRBL.RasterConverter.ConvertSizeAndOptionForm..ctor(GrblCore core) en E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:línea 49
   en LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) en E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:línea 179
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
