### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by Deanborgmann** [arkypita/LaserGRBL#1984]
LaserGrbl v4.9.3.0
Grbl v1.1h
Wrapper: UsbSerial
Win 10, Home, 10.0.22000.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.4515.0 built by: NET48REL1LAST_C

TypeOf exception  [System.OverflowException]
Exception message [Value was either too large or too small for an Int32.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Int32 ToInt32(System.Decimal)]

   ----------- stack trace -----------
   at System.Decimal.ToInt32(Decimal d)
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm.AssignMinMaxLimit() in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 78
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm..ctor(GrblCore core) in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 49
   at LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 179
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version
 - Engraver brand and model
 - Grbl version (i.e. 0.9j, 1.1f)
 - LaserGRBL version

**Additional context**

**Comment by LMH33** [comment]
did you fix this error? Help me
