### ISSUE TITLE
Same problem here.  Any updates on a solution/workaround?

### ISSUE THREAD

**Issue by Thothipower** [arkypita/LaserGRBL#2236]
Same problem here.  Any updates on a solution/workaround?

LaserGrbl v5.4.0
Grbl v1.1
Windows 10 Pro, OS Build 19045.3324

Open D:\Hutch.svg
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at LaserGRBL.SvgConverter.GCodeFromSVG.parsePathCommand(String svgPath) in E:\LaserGRBL\LaserGRBL\SvgConverter\GCodeFromSVG.cs:line 667
at LaserGRBL.SvgConverter.GCodeFromSVG.parsePath(XElement svgCode, Int32 level) in E:\LaserGRBL\LaserGRBL\SvgConverter\GCodeFromSVG.cs:line 638
at LaserGRBL.SvgConverter.GCodeFromSVG.parseGroup(XElement svgCode, Int32 level) in E:\LaserGRBL\LaserGRBL\SvgConverter\GCodeFromSVG.cs:line 268
at LaserGRBL.SvgConverter.GCodeFromSVG.convertSVG(XElement svgCode, GrblCore core) in E:\LaserGRBL\LaserGRBL\SvgConverter\GCodeFromSVG.cs:line 96
at LaserGRBL.GrblFile.LoadImportedSVG(String filename, Boolean append, GrblCore core) in E:\LaserGRBL\LaserGRBL\GrblFile.cs:line 134
at LaserGRBL.SvgConverter.SvgToGCodeForm.CreateAndShowDialog(GrblCore core, String filename, Form parent, Boolean append) in E:\LaserGRBL\LaserGRBL\SvgConverter\ConvertSizeAndOptionForm.cs:line 47
at LaserGRBL.GrblCore.OpenFile(Form parent, String filename, Boolean append) in E:\LaserGRBL\LaserGRBL\Core\GrblCore.cs:line 659

![Hutch](https://github.com/arkypita/LaserGRBL/assets/64557538/c7bf140f-dcf6-45f1-9061-4ae6572f896f)

_Originally posted by @sheets999 in https://github.com/arkypita/LaserGRBL/issues/1969#issuecomment-1709098575_

**Comment by arkypita** [comment]
Update to latest version of LaserGRBL
