### ISSUE TITLE
*LaserGrbl v7.12.0.0

### ISSUE THREAD

**Issue by verolara100** [arkypita/LaserGRBL#2335]
*LaserGrbl v7.12.0.0
Grbl v1.1h
Wrapper: UsbSerial
Win 11, Professional, 10.0.22000.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.9195.0 built by: NET481REL1LAST_B

TypeOf exception  [System.ObjectDisposedException]
Exception message [Safe handle has been closed]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Void DangerousAddRef(Boolean ByRef)]

   ----------- stack trace -----------
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.UnsafeNativeMethods.GetOverlappedResult(SafeFileHandle hFile, NativeOverlapped* lpOverlapped, Int32& lpNumberOfBytesTransferred, Boolean bWait)
   at System.IO.Ports.SerialStream.EventLoopRunner.WaitForCommEvent()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ReggiePye** [comment]
I have this version on two computers. One uses Windows 10 and the other Windows 11.
The Windows 10 version has a steps slider for Z axis that works fine and has up and down increments.
The Windows 11  version (same exact setup as in Windows 10) has just a small Z and a small downward arrow. 
Why the difference?
