### ISSUE TITLE
lasertgrbl always locks up over night

### ISSUE THREAD

**Issue by skyhawkeye** [arkypita/LaserGRBL#2484]
This the error I always get. Thanks, T.H.
LaserGrbl v7.14.0.0
Wrapper: UsbSerial.
Win 10, Home, 10.0.19045.0 (7)
CLR: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll 4.8.9282.0 built by: NET481REL1LAST_C

TypeOf exception  [System.ObjectDisposedException]
Exception message [Safe handle has been closed]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Void DangerousAddRef(Boolean ByRef)]

   ----------- stack trace -----------
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.UnsafeNativeMethods.GetOverlappedResult(SafeFileHandle hFile, NativeOverlapped* lpOverlapped, Int32& lpNumberOfBytesTransferred, Boolean bWait)
   at System.IO.Ports.SerialStream.EventLoopRunner.WaitForCommEvent()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware and software configuration (please complete the following information):**
 - Windows version
 - Engraver brand and model
 - Grbl version (i.e. 0.9j, 1.1f)
 - LaserGRBL version

**Additional context**

**Comment by arkypita** [comment]
thanks to all

This DangerousAddRef error is inside a windows component System.IO.Ports.SerialStream that is not under my control, and I cannot fix it directly because it is not LaserGRBL code.

I suggest all of you to update the latest version of [Microsoft .NET framework](https://www.google.com/search?client=opera&q=Microsoft+.NET+framework&sourceid=opera&ie=UTF-8&oe=UTF-8) and if not work, to change in LaserGRBL settings from UsbSerial to RJCPSerial

![Image](https://github.com/user-attachments/assets/33a6b0ec-9cdd-46f6-a003-9780cfcd5c55)
