### ISSUE TITLE
Immediately disconnecting

### ISSUE THREAD

**Issue by xlblackinklx** [arkypita/LaserGRBL#519]
When I go to connect to my board, it will connect very briefly, then instantly disconnect.
I can connect without issues using CNCjs.  
Here is my session log:
`12/4/2018 9:55:41 AM	Program     	------- LaserGRBL v3.0.4 START -------
12/4/2018 9:55:44 AM	SetStatus   	Machine status [Disconnected]
12/4/2018 9:55:46 AM	SetStatus   	Machine status [Connecting]
12/4/2018 9:55:46 AM	OpenCom     	Open COM8 @ 115200 baud 
12/4/2018 9:55:46 AM	SendImmediate	Send Immediate Command [0x18]
12/4/2018 9:55:46 AM	VersionInfo 	Ex on [Grbl Gerbil 1.1e ['$' for help]] message
12/4/2018 9:55:46 AM	VersionInfo 	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:46 AM	VersionInfo 	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:46 AM	VersionInfo 	   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:46 AM	VersionInfo 	   at LaserGRBL.GrblCore.ManageVersionInfo(String rline)
12/4/2018 9:55:46 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:46 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:46 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:46 AM	SetStatus   	Machine status [Disconnected]
12/4/2018 9:55:46 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000] message
12/4/2018 9:55:46 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:46 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:46 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:46 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:46 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:46 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100] message
12/4/2018 9:55:46 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:46 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:46 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:46 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:46 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:46 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:46 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:46 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:46 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:46 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:46 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:46 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:46 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:46 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:46 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:47 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:47 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:47 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:47 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:47 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:47 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:47 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:47 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:47 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:47 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:47 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:47 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:47 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:47 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:47 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:47 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:47 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:47 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:47 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:47 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:47 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:47 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:47 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:47 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:47 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:47 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:47 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:47 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:47 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:47 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:47 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:48 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:48 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:48 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:48 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0] message
12/4/2018 9:55:48 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:48 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
12/4/2018 9:55:48 AM	ParseMachineStatus	System.ArgumentException: Requested value 'Idle|MPos' was not found.
12/4/2018 9:55:48 AM	ParseMachineStatus	   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
12/4/2018 9:55:48 AM	ParseMachineStatus	   at LaserGRBL.GrblCore.ParseMachineStatus(String data)
12/4/2018 9:55:48 AM	RealTimeStatus	Ex on [Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000] message
12/4/2018 9:55:48 AM	RealTimeStatus	System.FormatException: Input string was not in a correct format.
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
12/4/2018 9:55:48 AM	RealTimeStatus	   at System.Single.Parse(String s, NumberStyles style, NumberFormatInfo info)
12/4/2018 9:55:48 AM	RealTimeStatus	   at LaserGRBL.GrblCore.ManageRealTimeStatus(String rline)
`

**Comment by arkypita** [comment]
The message "Grbl **Gerbil** 1.1e" is not recognized by LaserGRBL as a valid welcome message because of **Gerbil** that is not standard: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#grbl-push-messages

The status message [Idle|MPos:0.000,0.000,0.000|FS:0,0] is not valid because of the use of square bracket. Valid status report are enclosed between < >. Referee to original grbl documentation: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports

LaserGRBL claim to be 100% compatible with original Grbl firmware from https://github.com/gnea/grbl/ and it is. If third party firmware exist they should respect those specifications, however LaserGRBL cannot work on it.
