### ISSUE TITLE
windows 7 Import Raster Image import using centerline tool

### ISSUE THREAD

**Issue by benjjyman** [arkypita/LaserGRBL#758]
HI thanks so much for the application, its been a real pleasure to explore a new hobby.

I have stumbled across one issue when trying to import an image using a 32 bit version of windows 7, is this feature available on later issues of windows as if there is not a fix I will update this operating system preferably to Linux :)

28/10/2019 23:23:31	Program     	------- LaserGRBL v3.0.17 START -------
28/10/2019 23:23:33	SetStatus   	Machine status [Disconnected]
28/10/2019 23:23:46	OpenFile    	Open C:\Users\lyd\Desktop\maxresdefault.jpg
28/10/2019 23:23:57	Centerline  	System.ComponentModel.Win32Exception: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher
28/10/2019 23:23:57	Centerline  	   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
28/10/2019 23:23:57	Centerline  	   at System.Diagnostics.Process.Start()
28/10/2019 23:23:57	Centerline  	   at LaserGRBL.Autotrace.ExecuteAutotrace(String args)
28/10/2019 23:23:57	Centerline  	   at LaserGRBL.Autotrace.BitmapToSvgString(Bitmap bmp, Boolean uct, Int32 ct, Boolean ult, Int32 lt)
28/10/2019 23:23:57	Centerline  	   at LaserGRBL.GrblFile.LoadImageCenterline(Bitmap bmp, String filename, Boolean useCornerThreshold, Int32 cornerThreshold, Boolean useLineThreshold, Int32 lineThreshold, L2LConf conf, Boolean append)

**Comment by arkypita** [comment]
Hi @benjjyman 
Centerline tracing in LaserGRBL use an external executable called "autotrace.exe" that I have only found as precompiled binary for 64bit version of windows. Other versions needs a lot of external dependencies and source code is not easily to build. 

So, for now, autotrace only work on x64 version of windows.
