### ISSUE TITLE
There was a program error due to some unexpected condition.......

### ISSUE THREAD

**Issue by musialjacek** [arkypita/LaserGRBL#983]
LaserGrbl v3.3.1.0
Grbl v1.1f
Wrapper: UsbSerial
Win 7, Ultimate, 5.1.2600.0 (0)

TypeOf exception  [System.OverflowException]
Exception message [Value was either too large or too small for an Int32.]
Exception source  [mscorlib], thread [Main Thread]
Exception method  [Int32 ToInt32(System.Decimal)]

   ----------- stack trace -----------
   at System.Decimal.ToInt32(Decimal d)
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm.AssignMinMaxLimit() in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 62
   at LaserGRBL.RasterConverter.ConvertSizeAndOptionForm..ctor(GrblCore core) in E:\LaserGRBL\LaserGRBL\RasterConverter\ConvertSizeAndOptionForm.cs:line 31
   at LaserGRBL.RasterConverter.RasterToLaserForm.BtnCreateClick(Object sender, EventArgs e) in E:\LaserGRBL\LaserGRBL\RasterConverter\RasterToLaserForm.cs:line 177
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by arkypita** [comment]
What number do you have here?

![image](https://user-images.githubusercontent.com/8782035/80728754-93dd3080-8b07-11ea-9946-fd635a29cafa.png)

Look like you have a very huge number.
